### ISSUE TITLE
How can I install Alchemist, Occultist, and Sorcerer permanently without the UXP Developer Tool?

### ISSUE THREAD

**Issue by visusys** [jardicc/alchemist#28] opened 2022-07-25 01:44 UTC
Question is title. I can load it via the UXP tool, but I want to have it active permanently.

How do I do this?

**Comment by jardicc** [comment] 2022-08-01 00:42
Duplicate of https://github.com/jardicc/alchemist/issues/29

**Closed by jardicc** 2022-08-01 00:42 UTC
