### ISSUE TITLE
@types/photoshop not found when npm install

### ISSUE THREAD

**Issue by bit-pete** [jardicc/alchemist#12] opened 2021-01-14 13:01 UTC
when npm install it show this error
"fatal: repository 'https://github.com/adobe-uxp/types-photoshop.git/' not found"
Is this path still exist or use other path

**Comment by jardicc** [comment] 2021-02-07 19:45
duplicate of: https://github.com/jardicc/alchemist/issues/7

**Comment by jardicc** [comment] 2021-11-16 20:41
I am implementing official UXP-PS types https://twitter.com/J_Bereza/status/1458910672629157897

**Closed** 2022-04-21 10:55 UTC
